<?php
/** @var \Magento\Customer\Block\Account\Dashboard $block */
/** @var \Magento\Framework\Escaper $escaper */
/** @var \Vitaly\Hobby\ViewModel\Customer\Hobby $viewModel */
$viewModel = $block->getData('viewModel');
?>
<form class="form form-hobby-manage" action="<?= $escaper->escapeUrl($viewModel->getAction()) ?>" method="post"
      id="form-validate">
    <fieldset class="fieldset">
        <?= $block->getBlockHtml('formkey') ?>
        <div class="field choice">
            <select id="hobby-options" name="hobby" class="hobby-options">
                <?php foreach ($viewModel->getAllOptions() as $option): ?>
                    <option value="<?= /* @noEscape */ $option['value'] ?>"
                        <?php if ($viewModel->isSelectedOption((int) $option['value'])): ?>
                            selected="selected"
                        <?php endif; ?>>
                        <?= $escaper->escapeHtml($option['label']) ?>
                    </option>
                <?php endforeach; ?>
            </select>
        </div>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit" title="<?= $escaper->escapeHtmlAttr(__('Save')) ?>"
                    class="action save primary">
                <span><?= $escaper->escapeHtml(__('Save')) ?></span></button>
        </div>
        <div class="secondary">
            <a class="action back" href="<?= $escaper->escapeUrl($block->getBackUrl()) ?>">
                <span><?= $escaper->escapeHtml(__('Back')) ?></span>
            </a>
        </div>
    </div>
</form>
